# your essential settings
title: Y-E-S Fest 2018
email: mail@y-e-s.org
url: https://2018.y-e-s.org
description: "Festival for experimental scores, 29.-30.09.18 @ Agora, Berlin"

sass:
  sass_dir: assets/styles
  style: compressed

markdown: kramdown

collections:
  - artists
  - saturday
  - sunday
