# your essential settings
title: Y-E-S Fest 2018
email: mail@y-e-s.org
description: To celebrate its first year of existence, the collective is organizing Y-E-S Fest at Agora, 29.09 - 30.09. in Berlin.

sass:
  sass_dir: assets/styles
  style: compressed

markdown: kramdown
